
server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/books?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallback-to-system-locale: false
    mvc:
      locale: en
      locale-resolver: fixed

api:
  prefix: api/v1
jwt:
  expiration: 2592000  #30 days
  #  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=
  secretKey: R3Nj9XO1xOiT5X4B3qlvRMnmrkXo2LbGVYWrlfL1A7U=
